server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/shafiq/self-study/microservices-in-acction-book/configurationserver/src/main/resources/config/licensingservice
